stages:
  - lint
  - test

variables:
  DOCKER_IMAGE: alpine:latest
  UV_LINK_MODE: copy
  GIT_DEPTH: 0

default:
  tags:
    - geopy

include:
  - local: '.gitlab/templates/pre-commit.yml'
  - local: '.gitlab/templates/auto-bump.yml'
  - local: '.gitlab/templates/test.yml'
  - local: '.gitlab/templates/deploy.yml'
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

pre-commit:
  extends: .pre-commit-template
  variables:
    GIT_USER_EMAIL: "ci-runner@icf.gob.hn"
    GIT_USER_NAME: "ICF CI Runner"
    GIT_BOT_USER: "${CI_NOPROTECTED_BOT_USER}"
    GIT_TOKEN_VAR: "CI_NOPROTECTED_TOKEN"
    GIT_REPO_URL: "https://${CI_NOPROTECTED_BOT_USER}:${CI_NOPROTECTED_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"


sast:
  extends: default

secret_detection:
  extends: default
  image: registry.gitlab.com/security-products/secrets:7
